# Generated by Django 5.2.1 on 2025-07-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contactinfo_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': "Aloqa ma'lumoti", 'verbose_name_plural': "Aloqa ma'lumotlari"},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tiktok_link',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
    ]
