# Generated by Django 5.2.1 on 2025-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('color', models.CharField(default='emerald', help_text='Tailwind rang nomi faqat: rose, amber, emerald, sky va h.k.', max_length=20)),
            ],
        ),
    ]
