# Generated by Django 5.2.1 on 2025-07-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(choices=[('emerald', 'Yashil'), ('blue', 'Ko‘k'), ('rose', 'Qizil'), ('yellow', 'Sariq'), ('purple', 'Binafsha')], default='emerald', max_length=20),
        ),
    ]
