# Generated by Django 5.2.1 on 2025-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hujjat nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('icon', models.CharField(default='📄', max_length=10, verbose_name='Emoji yoki Icon')),
            ],
        ),
    ]
