# Generated by Django 5.2.1 on 2025-07-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Izoh matni')),
                ('background_image', models.ImageField(upload_to='home_banners/', verbose_name='Fon rasmi')),
            ],
        ),
    ]
