# Generated by Django 5.2.1 on 2025-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platforma nomi (masalan: Instagram)')),
                ('icon', models.ImageField(upload_to='social_icons/', verbose_name='Ikonka (rasm)')),
                ('link', models.URLField(verbose_name='Havola')),
                ('bg_color', models.CharField(max_length=50, verbose_name='Fon rangi (masalan: bg-pink-500 yoki bg-gradient-to-r from-rose-500 to-pink-500)')),
                ('text_color', models.CharField(default='text-white', max_length=50, verbose_name='Matn rangi (masalan: text-white)')),
            ],
        ),
    ]
