# Generated by Django 5.2.1 on 2025-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialmediacard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='StudyToKorea', max_length=255)),
                ('name', models.CharField(default='StudyToKorea', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('footer_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
